# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 120

# https://github.com/hhatto/autopep8#usage
# https://github.com/hhatto/autopep8#more-advanced-usage
[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3

# https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-pyprojecttoml-file
[tool.pyright]
# TODO: Fix everything and set to strict
typeCheckingMode = "basic"
# Extra strict
reportImplicitStringConcatenation="error"
reportCallInDefaultInitializer="error"
reportMissingSuperCall="none" # False positives on base classes
reportPropertyTypeMismatch="error"
reportUninitializedInstanceVariable="error"
reportUnnecessaryTypeIgnoreComment="error"
reportUnusedCallResult="none"
exclude = [
  "typings/",
]
reportMissingTypeStubs = "warning"
# False positives with TYPE_CHECKING
reportImportCycles = "information"
# Extra runtime safety
reportUnnecessaryComparison = "warning"
# Flake8 does a better job
reportUnusedImport = "none"
# numpy has way too many complex types that triggers this
reportUnknownMemberType = "none"

# https://github.com/PyCQA/pylint/blob/main/examples/pylintrc
# https://pylint.pycqa.org/en/latest/technical_reference/features.html
[tool.pylint.REPORTS]
# Just like default but any error will make drop to 9 or less. warning and conventions are worth more
evaluation = "10.0 - error - ((float((warning + convention) * 10 + refactor ) / statement) * 10)"
[tool.pylint.MASTER]
fail-under = 9.0
# Needed for Pylint to discover our own modules
init-hook = "import os, sys; sys.path.append(os.path.dirname('.'))"
# https://pylint.pycqa.org/en/latest/technical_reference/extensions.html
load-plugins = [
  "pylint.extensions.emptystring",
  "pylint.extensions.confusing_elif",
  "pylint.extensions.consider_ternary_expression",
  "pylint.extensions.bad_builtin",
  "pylint.extensions.mccabe",
  "pylint.extensions.check_elif",
  "pylint.extensions.redefined_variable_type",
  "pylint.extensions.overlapping_exceptions",
  "pylint.extensions.empty_comment",
  "pylint.extensions.set_membership",
  "pylint.extensions.typing",
  # External plugins
  "pylint_flask",
  "pylint_flask_sqlalchemy",
  # TODO: Maybe later
  # "pylint.extensions.docparams",
  # Not wanted/needed
  # "pylint.extensions.broad_try_clause",
  # "pylint.extensions.code_style",
  # "pylint.extensions.comparetozero",
  # "pylint.extensions.docstyle",
  # "pylint.extensions.while_used",
  # Didn't work
  # "pylint.extensions.comparison_placement",
  # "pylint.extensions.for_any_all",
]
ignore-paths = [
  # We expect stub files to be incomplete or contain useless statements
  "^.*\\.pyi$",
]
# Dynamic/Generated members from SQLAlchemy
ignored-classes = ["scoped_session"]

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint.DESIGN]
# Same as SonarLint
max-args = 7
# Arbitrary to 2 bytes
max-attributes = 15
max-locals = 15

[tool.pylint.'MESSAGES CONTROL']
# Same as SonarLint
max-complexity = 15
# At least same as max-complexity
max-branches = 15
# https://pylint.pycqa.org/en/latest/user_guide/options.html#naming-styles
module-naming-style = "any"
# Can't make private class with PascalCase
class-rgx = "_?_?[a-zA-Z]+?$"
# https://github.com/PyCQA/pylint/issues/2018
good-names = ["id", "x", "y", "a0", "i", "t0", "t1", "fn", "pb", "wr"]
disable = [
  # No need to mention the fixmes
  "fixme",
  "missing-docstring",
  # We group imports
  "wrong-import-position",
  # Already taken care of and grayed out. Also conflicts with Pylance reportIncompatibleMethodOverride
  "unused-argument",
  # Already taken care of by Flake8
  "unused-import",
  # Similar lines in 2 files, doesn't really work
  "R0801",
  # TODO: Diabled until using *proper* class based logic
  "protected-access",
  # Strings are ok. Pylance also doesn't seem to see our overriden Exception classes
  "invalid-sequence-index",
  # Happens too often with Flask, child classes should not be affected by this rule
  # See: https://github.com/PyCQA/pylint/issues/4352
  "too-few-public-methods",
  # Too many false positives with Columns[]
  # https://github.com/PyCQA/pylint/issues/3979#issuecomment-1036936661
  # https://github.com/PyCQA/pylint/issues/4369#issuecomment-1036932987
  "unsubscriptable-object",
]

[tool.isort]
line_length = 120
combine_as_imports = true
