# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint Python
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**.py"
      - "**.pyi"
      - ".github/workflows/lint-python.yml"
      - "scripts/requirements*.txt"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.py"
      - "**.pyi"
      - ".github/workflows/lint-python.yml"
      - "scripts/requirements*.txt"

env:
  # https://help.pythonanywhere.com/pages/ChangingSystemImage/#available-python-versions-for-system-images
  python-version: "3.10"
  # https://help.pythonanywhere.com/pages/ChangingSystemImage/#base-ubuntu-version-for-each-system-image
  # runs-on: "ubuntu-20.04"

jobs:
  # Jobs that don't need dependencies installed
  isort:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements-dev.txt"
      - run: pip install isort
      - run: isort backend/ typings/ --check-only
  add-trailing-comma:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements-dev.txt"
      - run: pip install add-trailing-comma
      - run: add-trailing-comma $(git ls-files '**.py*') --py36-plus
  Bandit:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements-dev.txt"
      - run: pip install bandit
      - run: bandit -n 1 --severity-level medium --recursive backend

  # Jobs that do need dependencies installed
  Pyright:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r "scripts/requirements-dev.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - uses: jakebailey/pyright-action@v1
        with:
          working-directory: backend/
          extra-args: --warnings
  Pylint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r "scripts/requirements-dev.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - run: pylint backend/ --reports=y --output-format=colorized
  Flake8:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements-dev.txt"
      - run: pip install -r "scripts/requirements-dev.txt"
      - run: flake8 backend/ typings/
