# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint Python
on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "**.pyi"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.py"
      - "**.pyi"

env:
  python-version: "3.10"

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r "scripts/requirements.txt"
      - name: Analysing the code with ${{ job.name }}
        run: isort backend/ typings/ --check-only
  add-trailing-comma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - run: pip install add-trailing-comma
      - name: Analysing the code with ${{ job.name }}
        run: add-trailing-comma $(git ls-files '**.py*') --py36-plus
  Bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - run: pip install bandit
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        run: bandit -n 1 --severity-level medium --recursive backend
  Pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r "scripts/requirements.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        uses: jakebailey/pyright-action@v1
        with:
          working-directory: backend/
          extra-args: --warnings
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r "scripts/requirements.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        run: pylint backend/ --reports=y --output-format=colorized
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r "scripts/requirements.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        run: flake8 backend/ typings/
