# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint and build Tournament Scheduler
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "tournament-scheduler/**"
      - ".github/workflows/lint-and-build-tournament-scheduler.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "tournament-scheduler/**"
      - ".github/workflows/lint-and-build-tournament-scheduler.yml"
jobs:
  ESLint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tournament-scheduler
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tournament-scheduler
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build:no-compress
