# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint and build Tournament Scheduler
on:
  push:
    branches:
      - main
    paths:
      - 'tournament-scheduler/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'tournament-scheduler/**'
jobs:
  ESLint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tournament-scheduler
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tournament-scheduler
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build
