# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint Python
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.pyi'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.py'
      - '**.pyi'
jobs:
  Pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r "scripts/requirements.txt"
          npm install -g pyright
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        run: pyright --warnings backend
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r "scripts/requirements.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        run: pylint --reports=y --output-format=colorized $(git ls-files 'backend/*.py')
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r "scripts/requirements.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        run: flake8 backend
  Bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r "scripts/requirements.txt"
      - run: mv backend/configs.template.py backend/configs.py
      - name: Analysing the code with ${{ job.name }}
        run: bandit -n 1 --severity-level medium --recursive backend
